### ISSUE TITLE
Error on varnish:flush command

### ISSUE THREAD

**Issue by Nuranto** [spatie/laravel-varnish#48]
```
Argument 1 passed to Symfony\Component\Process\Process::__construct() must be of the type array, string given, called in /[...]/vendor/spatie/laravel-varnish/src/Varnish.php on line 66 
```

Laravel 7 (latest)
Laravel-varnish 2.8.1 (latest)

**Comment by Nuranto** [comment]
Probable duplicate of #46

**Comment by nathanwinther** [comment]
Also getting error on `php artisan varnish:flush`

```
Argument 1 passed to Symfony\Component\Process\Process::__construct() must be of the type array, string given, called in vendor/spatie/laravel-varnish/src/Varnish.php on line 66

  at vendor/symfony/process/Process.php:141
    137▕      * @param int|float|null $timeout The timeout in seconds or null to disable
    138▕      *
    139▕      * @throws LogicException When proc_open is not installed
    140▕      */
  ➜ 141▕     public function __construct(array $command, string $cwd = null, array $env = null, $input = null, ?float $timeout = 60)
    142▕     {
    143▕         if (!\function_exists('proc_open')) {
    144▕             throw new LogicException('The Process class relies on proc_open, which is not available on your PHP installation.');
    145▕         }

      +16 vendor frames 
  17  artisan:37
      Illuminate\Foundation\Console\Kernel::handle()
```

Laravel: v8.x
Symfony: v5.2

`new Process(string)` was Symfony v2.x
`new Process(array)` has been signature since 3.0

I have solved my adding my own class and console command and changing `generateBanCommand` and `executeCommand`

[Varnish.txt](https://github.com/spatie/laravel-varnish/files/6192288/Varnish.txt)

**Comment by Adrion** [comment]
Sadly this issue is still happening...

Laravel 8.x requires Symfony/process 5.4
If you check Process class signature : 
`public function __construct(array $command, string $cwd = null, array $env = null, $input = null, ?float $timeout = 60)`
And `Spatie\Varnish\Varnish` still uses string type for command property.

it looks like @Daniyal-Javani started some fixes regarding this issue but never made a PR ?

**Comment by Daniyal-Javani** [comment]
> it looks like @Daniyal-Javani started some fixes regarding this issue but never made a PR ?

It has been closed due to inactivity or probably it wasn't good enough and you can improve it: https://github.com/spatie/laravel-varnish/pull/49
